// UI **************************************************************************************
export const THEME_SET_PURPLE = 'THEME_SET_PURPLE'
export const THEME_SET_RED = 'THEME_SET_RED'
export const THEME_SET_BLUE = 'THEME_SET_BLUE'

export const ALERT_ADD = 'ALERT_ADD'
export const ALERT_REMOVE = 'ALERT_REMOVE'

// USER ****************************************************************************************
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST'
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS'
export const USER_FETCH_FAIL = 'USER_FETCH_FAIL'

export const USER_FETCH_CONTACT_REQUEST = 'USER_FETCH_CONTACT_REQUEST'
export const USER_FETCH_CONTACT_SUCCESS = 'USER_FETCH_CONTACT_SUCCESS'
export const USER_FETCH_CONTACT_FAIL = 'USER_FETCH_CONTACT_FAIL'

export const USER_FETCH_PRODUCTS_REQUEST = 'USER_FETCH_PRODUCTS_REQUEST'
export const USER_FETCH_PRODUCTS_SUCCESS = 'USER_FETCH_PRODUCTS_SUCCESS'
export const USER_FETCH_PRODUCTS_FAIL = 'USER_FETCH_PRODUCTS_FAIL'

export const USER_FETCH_BIDS_REQUEST = 'USER_FETCH_BIDS_REQUEST'
export const USER_FETCH_BIDS_SUCCESS = 'USER_FETCH_BIDS_SUCCESS'
export const USER_FETCH_BIDS_FAIL = 'USER_FETCH_BIDS_FAIL'

export const USER_FETCH_FOLLOWING_REQUEST = 'USER_FETCH_FOLLOWING_REQUEST'
export const USER_FETCH_FOLLOWING_SUCCESS = 'USER_FETCH_FOLLOWING_SUCCESS'
export const USER_FETCH_FOLLOWING_FAIL = 'USER_FETCH_FOLLOWING_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const COLLEGE_FETCH_ALL_REQUEST = 'COLLEGE_FETCH_ALL_REQUEST'
export const COLLEGE_FETCH_ALL_SUCCESS = 'COLLEGE_FETCH_ALL_SUCCESS'
export const COLLEGE_FETCH_ALL_FAIL = 'COLLEGE_FETCH_ALL_FAIL'

// PRODUCT **************************************************************************************
export const PRODUCT_FETCH_ALL_REQUEST = 'PRODUCT_FETCH_ALL_REQUEST'
export const PRODUCT_FETCH_ALL_SUCCESS = 'PRODUCT_FETCH_ALL_SUCCESS'
export const PRODUCT_FETCH_ALL_FAIL = 'PRODUCT_FETCH_ALL_FAIL'

export const PRODUCT_UPLOAD_REQUEST = 'PRODUCT_UPLOAD_REQUEST'
export const PRODUCT_UPLOAD_SUCCESS = 'PRODUCT_UPLOAD_SUCCESS'
export const PRODUCT_UPLOAD_FAIL = 'PRODUCT_UPLOAD_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_EDIT_REQUEST = 'PRODUCT_EDIT_REQUEST'
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS'
export const PRODUCT_EDIT_FAIL = 'PRODUCT_EDIT_FAIL'

export const PRODUCT_SEARCH_REQUEST = 'PRODUCT_SEARCH_REQUEST'
export const PRODUCT_SEARCH_SUCCESS = 'PRODUCT_SEARCH_SUCCESS'
export const PRODUCT_SEARCH_FAIL = 'PRODUCT_SEARCH_FAIL'
export const PRODUCT_SEARCH_CLEANUP = 'PRODUCT_SEARCH_CLEANUP'

export const PRODUCT_SINGLE_FETCH_REQUEST = 'PRODUCT_SINGLE_FETCH_REQUEST'
export const PRODUCT_SINGLE_FETCH_SUCCESS = 'PRODUCT_SINGLE_FETCH_SUCCESS'
export const PRODUCT_SINGLE_FETCH_FAIL = 'PRODUCT_SINGLE_FETCH_FAIL'
export const PRODUCT_SINGLE_CLEANUP = 'PRODUCT_SINGLE_CLEANUP'

// BID ******************************************************************************************
export const BID_PLACE_REQUEST = 'BID_PLACE_REQUEST'
export const BID_PLACE_SUCCESS = 'BID_PLACE_SUCCESS'
export const BID_PLACE_FAIL = 'BID_PLACE_FAIL'

export const BID_DELETE_REQUEST = 'BID_DELETE_REQUEST'
export const BID_DELETE_SUCCESS = 'BID_DELETE_SUCCESS'
export const BID_DELETE_FAIL = 'BID_DELETE_FAIL'

export const BID_STATUS_UPDATE_REQUEST = 'BID_STATUS_UPDATE_REQUEST'
export const BID_STATUS_UPDATE_SUCCESS = 'BID_STATUS_UPDATE_SUCCESS'
export const BID_STATUS_UPDATE_FAIL = 'BID_STATUS_UPDATE_FAIL'

export const BID_PRICE_UPDATE_REQUEST = 'BID_PRICE_UPDATE_REQUEST'
export const BID_PRICE_UPDATE_SUCCESS = 'BID_PRICE_UPDATE_SUCCESS'
export const BID_PRICE_UPDATE_FAIL = 'BID_PRICE_UPDATE_FAIL'

// FOLLOW/UNFOLLOW PRODUCT ********************************************************************
export const PRODUCT_FOLLOW_TOGGLE_REQUEST = 'PRODUCT_FOLLOW_TOGGLE_REQUEST'
export const PRODUCT_FOLLOW_TOGGLE_SUCCESS = 'PRODUCT_FOLLOW_TOGGLE_SUCCESS'
export const PRODUCT_FOLLOW_TOGGLE_FAIL = 'PRODUCT_FOLLOW_TOGGLE_FAIL'

// CONTACT FORM ********************************************************************************
export const CONTACT_MAIL_REQUEST = 'CONTACT_MAIL_REQUEST'
export const CONTACT_MAIL_SUCCESS = 'CONTACT_MAIL_SUCCESS'
export const CONTACT_MAIL_FAIL = 'CONTACT_MAIL_FAIL'

// NOTIFICATION ********************************************************************************
export const NOTIFICATION_LOGIN_AND_LOGOUT_ACTION_REQUEST =
    'NOTIFICATION_LOGIN_AND_LOGOUT_ACTION_REQUEST'
export const NOTIFICATION_LOGIN_AND_LOGOUT_ACTION_SUCCESS =
    'NOTIFICATION_LOGIN_AND_LOGOUT_ACTION_SUCCESS'
export const NOTIFICATION_LOGIN_AND_LOGOUT_ACTION_FAIL =
    'NOTIFICATION_LOGIN_AND_LOGOUT_ACTION_FAIL'

export const NOTIFICATION_GET_SAVED_REQUEST = 'NOTIFICATION_GET_SAVED_REQUEST'
export const NOTIFICATION_GET_SAVED_SUCCESS = 'NOTIFICATION_GET_SAVED_SUCCESS'
export const NOTIFICATION_GET_SAVED_FAIL = 'NOTIFICATION_GET_SAVED_FAIL'

export const NOTIFICATION_DELETE_REQUEST = 'NOTIFICATION_DELETE_REQUEST'
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS'
export const NOTIFICATION_DELETE_FAIL = 'NOTIFICATION_DELETE_FAIL'

export const NOTIFICATION_PUSH_NEW = 'NOTIFICATION_PUSH_NEW'
export const NOTIFICATION_UPDATE_READ = 'NOTIFICATION_UPDATE_READ'
export const NOTIFICATION_REMOVE_DELETED = 'NOTIFICATION_REMOVE_DELETED'

// UPDATE STORE *********************************************************************************
export const USER_UPDATE_UPDATED = 'USER_UPDATE_UPDATED'
export const USER_PRODUCT_PUSH_NEW = 'USER_PRODUCT_PUSH_NEW'
export const USER_PRODUCT_UPDATE_EDITED = 'USER_PRODUCT_UPDATE_EDITED'
export const USER_PRODUCT_REMOVE_DELETED = 'USER_PRODUCT_REMOVE_DELETED'
export const USER_BID_PUSH_NEW = 'USER_BID_PUSH_NEW'
export const USER_BID_REMOVE_DELETED = 'USER_BID_REMOVE_DELETED'
export const USER_BID_UPDATE_UPDATED_STATUS = 'USER_BID_UPDATE_UPDATED_STATUS'
export const USER_BID_UPDATE_UPDATED_PRICE = 'USER_BID_UPDATE_UPDATED_PRICE'
export const USER_FOLLOWING_UPDATE = 'USER_FOLLOWING_UPDATE'
export const USER_POPULATE_PRODUCTS = 'USER_POPULATE_PRODUCTS'
export const USER_POPULATE_BIDS = 'USER_POPULATE_BIDS'
export const USER_POPULATE_FOLLOWING = 'USER_POPULATE_FOLLOWING'
export const USER_FOLLOWING_UPDATE_ON_BID_PLACE = 'USER_FOLLOWING_UPDATE_ON_BID_PLACE'
export const USER_NOTIFICATION_PRODUCT_UPDATE = 'USER_NOTIFICATION_PRODUCT_UPDATE'

export const PRODUCT_REMOVE_DELETED = 'PRODUCT_REMOVE_DELETED'
export const PRODUCT_PUSH_NEW = 'PRODUCT_PUSH_NEW'
export const PRODUCT_UPDATE_EDITED = 'PRODUCT_UPDATE_EDITED'
export const PRODUCT_NOTIFICATION_PRODUCT_UPDATE = 'PRODUCT_NOTIFICATION_PRODUCT_UPDATE'

export const BID_REMOVE_DELETED = 'BID_REMOVE_DELETED'
export const BID_PUSH_NEW = 'BID_PUSH_NEW'
export const BID_UPDATE_UPDATED_STATUS = 'BID_UPDATE_UPDATED_STATUS'
export const BID_UPDATE_UPDATED_PRICE = 'BID_UPDATE_UPDATED_PRICE'

export const PRODUCT_SINGLE_REMOVE_DELETED = 'PRODUCT_SINGLE_REMOVE_DELETED'
export const PRODUCT_SINGLE_BID_PUSH_NEW = 'PRODUCT_SINGLE_BID_PUSH_NEW'
export const PRODUCT_SINGLE_BID_REMOVE_DELETED = 'PRODUCT_SINGLE_BID_REMOVE_DELETED'
export const PRODUCT_SINGLE_BID_UPDATE_UPDATED_PRICE =
    'PRODUCT_SINGLE_BID_UPDATE_UPDATED_PRICE'
export const PRODUCT_SINGLE_BID_UPDATE_UPDATED_STATUS =
    'PRODUCT_SINGLE_BID_UPDATE_UPDATED_STATUS'

// CLEAN-UP ************************************************************************************
export const PRODUCT_CLEANUP = 'PRODUCT_CLEANUP'
export const USER_PRODUCTS_CLEANUP = 'USER_PRODUCTS_CLEANUP'
export const USER_BIDS_CLEANUP = 'USER_BIDS_CLEANUP'
export const USER_FOLLOWING_CLEANUP = 'USER_FOLLOWING_CLEANUP'
export const NOTIFICATION_CLEANUP = 'NOTIFICATION_CLEANUP'
